import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const names = {
  offering: "KiranaOffering",
  registry: "EligibilityRegistry",
  kira: "EquityLinkedToken",
  marketplace: "SecondaryMarketplace",
  currency: "DemoUSDC",
  demoAccess: "DemoAccess",
};
const output = Object.entries(names).map(([name, contract]) => {
  const artifact = JSON.parse(readFileSync(resolve(root, `packages/contracts/out/${contract}.sol/${contract}.json`), "utf8"));
  return `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`;
});
mkdirSync(resolve(root, "packages/chain/src"), { recursive: true });
writeFileSync(resolve(root, "packages/chain/src/abi.ts"), `// Generated by scripts/export-abi.mjs from Foundry artifacts.\n${output.join("\n\n")}\n`);
console.log("Exported ABIs for six SAMA contracts.");
